on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'
      - name: "Download tools and dependencies"
        run: 
          make download-tools && go get
      - name: "Build plugin"
        run: >
            make build || exit 1
        # run: >
        #   cat ci/SUPPORTED_VERSIONS.txt | while read TARGET; do
        #       make GOTIFY_VERSION="$TARGET" FILE_SUFFIX="-for-gotify-$TARGET" build || exit 1
        #   done
      - name: "Upload plugin"
        uses: actions/upload-artifact@v4
        with:
          name: gotify-smtp-emailer
          path: build
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*"
