on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'
      - name: "Download tools and dependencies"
        run: 
          make download-tools && go get
      - name: "Build"
        run: >
            make build || exit 1
      - name: Test
        run: go test -v ./...
