name: "Test Plugin"

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test plugin
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - name: "Download tools and dependencies"
        run: 
          make download-tools && go get -d
      - name: Test
        run: go test ./...
