name: "Test Plugin"
runs-on: self-hosted

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    name: Test plugin
    steps:
      - name: Test
        run: go test ./...
